# Generated by Django 4.2.9 on 2024-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="code",
        ),
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Code"
            ),
        ),
    ]
