# Generated by Django 4.2.9 on 2024-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_remove_city_code_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("User", "User"), ("Admin", "Administrateur")],
                default="User",
                max_length=100,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
