# Generated by Django 4.2.9 on 2024-01-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_city",
                to="main_app.city",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_country",
                to="main_app.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to="cv/%Y/%m/", verbose_name="CV"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Facebook Link"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
                verbose_name="Sexe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Instagram Link"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linked_in",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Linked In Link"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile/%Y/%m/", verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Twitter Link"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
